const products = [
  {
    id: 0,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
    emoji: '🎧',
    brand: 'Sony',
    name: 'WH-1000XM5',
    category: 'audio',
    tag: 'top',
    price: 349.99,
    original: 429.99,
    rating: 4.9,
    reviews: 2148,
    desc: 'Industry-leading noise cancellation with LDAC audio codec. 30-hour battery, multipoint connection and crystal-clear call quality for every environment.',
    specs: [
      ['Driver',       '30mm Dynamic'],
      ['Battery',      '30 hours'],
      ['Connectivity', 'Bluetooth 5.2'],
      ['Weight',       '250g'],
      ['Colors',       'Black, Silver'],
    ],
  },
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=600&q=80',
    emoji: '📱',
    brand: 'Apple',
    name: 'iPhone 16 Pro',
    category: 'phones',
    tag: 'new',
    price: 999.99,
    original: null,
    rating: 4.8,
    reviews: 3412,
    desc: 'A18 Pro chip, 48MP camera system, ProMotion 120Hz display, titanium design and Apple Intelligence built in.',
    specs: [
      ['Chip',    'A18 Pro'],
      ['Display', '6.3" Super Retina XDR'],
      ['Camera',  '48MP + 12MP Ultra Wide'],
      ['Storage', '256GB – 1TB'],
      ['Battery', 'All-day'],
    ],
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80',
    emoji: '💻',
    brand: 'Apple',
    name: 'MacBook Pro M4',
    category: 'laptops',
    tag: 'top',
    price: 1999.99,
    original: 2299.99,
    rating: 4.9,
    reviews: 1204,
    desc: 'M4 Pro chip with 12-core CPU, 120Hz Liquid Retina XDR display, up to 24GB unified memory and 22-hour battery.',
    specs: [
      ['Chip',    'Apple M4 Pro'],
      ['RAM',     '24GB Unified'],
      ['Storage', '512GB SSD'],
      ['Display', '14" Liquid Retina XDR'],
      ['Battery', '22 hours'],
    ],
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=600&q=80',
    emoji: '⌚',
    brand: 'Apple',
    name: 'Apple Watch Ultra 2',
    category: 'wearables',
    tag: 'new',
    price: 799.99,
    original: 849.99,
    rating: 4.8,
    reviews: 654,
    desc: 'Most rugged Apple Watch ever. Dual-frequency GPS, action button, depth gauge and up to 60-hour battery life.',
    specs: [
      ['Display', '49mm Always-On LTPO OLED'],
      ['GPS',     'Dual-frequency L1+L5'],
      ['Water',   '100m Resistance'],
      ['Battery', '60 hours'],
      ['Material','Titanium'],
    ],
  },
  {
    id: 4,
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&q=80',
    emoji: '📷',
    brand: 'Sony',
    name: 'ZV-E10 II',
    category: 'cameras',
    tag: 'sale',
    price: 749.99,
    original: 899.99,
    rating: 4.6,
    reviews: 432,
    desc: '26MP APS-C sensor, 4K 60fps video, AI autofocus and perfect for vlogging and content creation.',
    specs: [
      ['Sensor',  '26MP APS-C Exmor R'],
      ['Video',   '4K 60fps'],
      ['AF',      'AI Phase Detection'],
      ['Lens',    'Sony E-Mount'],
      ['Display', 'Vari-angle touchscreen'],
    ],
  },
  {
    id: 5,
    image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&q=80',
    emoji: '🎮',
    brand: 'Sony',
    name: 'PlayStation 5 Pro',
    category: 'phones',
    tag: 'top',
    price: 699.99,
    original: null,
    rating: 4.9,
    reviews: 5231,
    desc: 'PSSR rendering, ray tracing, 8K gaming capability and haptic DualSense controller for next-gen immersion.',
    specs: [
      ['CPU',        'AMD Zen 2 Custom'],
      ['GPU',        'AMD RDNA 2 Enhanced'],
      ['Storage',    '2TB SSD'],
      ['Resolution', 'Up to 8K'],
      ['Frame Rate', 'Up to 120fps'],
    ],
  },
  {
    id: 6,
    image: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=600&q=80',
    emoji: '💻',
    brand: 'Apple',
    name: 'MacBook Air M3 15"',
    category: 'laptops',
    tag: 'sale',
    price: 1099.99,
    original: 1499.99,
    rating: 4.9,
    reviews: 2341,
    desc: 'The deal of the day! Massive 15.3" Liquid Retina screen, M3 chip, 16GB RAM and 18-hour battery. Perfect for students.',
    specs: [
      ['Chip',    'Apple M3'],
      ['RAM',     '16GB'],
      ['Storage', '512GB SSD'],
      ['Display', '15.3" Liquid Retina'],
      ['Battery', '18 hours'],
    ],
  },
  {
    id: 7,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&q=80',
    emoji: '🎧',
    brand: 'Bose',
    name: 'QuietComfort 45',
    category: 'audio',
    tag: 'sale',
    price: 229.99,
    original: 329.99,
    rating: 4.7,
    reviews: 1432,
    desc: 'World-class noise cancellation, TriPort acoustic architecture, 24-hour battery life and Google Assistant.',
    specs: [
      ['Noise Cancel', 'Adaptive Quiet Mode'],
      ['Battery',      '24 hours'],
      ['Connectivity', 'Bluetooth 5.1'],
      ['Weight',       '238g'],
      ['Colors',       'Black, White'],
    ],
  },
  {
    id: 8,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80',
    emoji: '📱',
    brand: 'Samsung',
    name: 'Galaxy S25 Ultra',
    category: 'phones',
    tag: 'new',
    price: 1299.99,
    original: null,
    rating: 4.8,
    reviews: 2890,
    desc: '200MP camera, built-in S Pen, Snapdragon 8 Elite, 12GB RAM and 6.9" QHD+ Dynamic AMOLED display.',
    specs: [
      ['Chip',    'Snapdragon 8 Elite'],
      ['RAM',     '12GB'],
      ['Camera',  '200MP Quad System'],
      ['Display', '6.9" QHD+ 120Hz'],
      ['S Pen',   'Built-in'],
    ],
  },
  {
    id: 9,
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80',
    emoji: '⌚',
    brand: 'Samsung',
    name: 'Galaxy Watch 7',
    category: 'wearables',
    tag: 'new',
    price: 299.99,
    original: 349.99,
    rating: 4.6,
    reviews: 743,
    desc: 'Advanced health monitoring, sleep analysis, body composition, BioActive sensor and Galaxy AI features.',
    specs: [
      ['Display', '1.5" Super AMOLED'],
      ['Health',  'BioActive Sensor'],
      ['Battery', '40 hours'],
      ['Water',   '5ATM'],
      ['GPS',     'Multi-band'],
    ],
  },
  {
    id: 10,
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80',
    emoji: '📷',
    brand: 'Canon',
    name: 'EOS R50 Mark II',
    category: 'cameras',
    tag: 'top',
    price: 899.99,
    original: 999.99,
    rating: 4.7,
    reviews: 321,
    desc: '24MP APS-C CMOS sensor, 4K uncropped video, Eye AF tracking and a compact mirrorless body for creators.',
    specs: [
      ['Sensor', '24MP APS-C CMOS'],
      ['Video',  '4K Uncropped'],
      ['AF',     'Eye AF + Subject Tracking'],
      ['EVF',    '2.36M-dot'],
      ['Weight', '375g'],
    ],
  },
  {
    id: 11,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80',
    emoji: '🔊',
    brand: 'JBL',
    name: 'Charge 6',
    category: 'audio',
    tag: 'sale',
    price: 139.99,
    original: 199.99,
    rating: 4.5,
    reviews: 3211,
    desc: '360° stereo sound, 24-hour playtime, IP68 waterproof, powerbank function and PartyBoost stereo pairing.',
    specs: [
      ['Output',    '40W RMS'],
      ['Battery',   '24 hours'],
      ['Waterproof','IP68'],
      ['PowerBank', 'USB-A output'],
      ['Pairing',   'PartyBoost'],
    ],
  },
];
